export const Url = 'http://localhost:5000/api/v1'

export const REGISTER_USER_REQUEST ='REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS ='REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL ='REGISTER_USER_FAIL'

export const ENROLMENT_PATIENT_REQUEST ='ENROLMENT_PATIENT_REQUEST'
export const ENROLMENT_PATIENT_SUCCESS ='ENROLMENT_PATIENT_SUCCESS'
export const ENROLMENT_PATIENT_FAIL ='ENROLMENT_PATIENT_FAIL'
export const ENROLMENT_PATIENT_RESET ='ENROLMENT_PATIENT_RESET'

export const GET_ALL_PATIENT_REQUEST ='GET_ALL_PATIENT_REQUEST'
export const GET_ALL_PATIENT_SUCCESS ='GET_ALL_PATIENT_SUCCESS'
export const GET_ALL_PATIENT_FAIL ='GET_ALL_PATIENT_FAIL'
